#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
httpd -f ${OPENSHIFT_REPO_DIR}/conf/httpd.conf -k start
